# Generated by Django 4.2.4 on 2024-01-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='discription',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
